# Global parameters are not affected by symmetry, and thus not changed depending on the ligand symmetry.
global_bondval_parameters = [
    'Homo',
    'Lumo',
    'dipole',
    'Pd_NBO',
    'Pd_LP_1_occ',
    'Pd_LP_1_eng',
    'Pd_LP_2_occ',
    'Pd_LP_2_eng',
    'Pd_LP_3_occ',
    'Pd_LP_3_eng',
    'Pd_LP_4_occ',
    'Pd_LP_4_eng',
    'bite_angle',
    'NoPd_Homo',
    'NoPd_Lumo',
    'NoPd_dipole',
    'pol']
global_vbur_parameters = ['Vbur%_3.0_Ang', 'Vbur%_4.0_Ang', 'Vbur%_5.0_Ang', 'Vbur%_6.0_Ang', 'Vbur%_7.0_Ang']
global_parameters = global_bondval_parameters + global_vbur_parameters

# Parameters for ligands with a C1 symmetry
C1_dict = {
    ## Geometric parameters
    # Bond distances
    'Cl1-Pd_distance': ['Cl1-Pd_distance'],
    'Cl2-Pd_distance': ['Cl2-Pd_distance'],
    'P1_R1_distance': ['P1_R1_distance'],
    'P1_R2_distance': ['P1_R2_distance'],
    'P2_R3_distance': ['P2_R3_distance'],
    'P2_R4_distance': ['P2_R4_distance'],
    'P1_RBack1_distance': ['P1_RBack1_distance'],
    'P2_RBack2_distance': ['P2_RBack2_distance'],
    'P1-Pd_distance': ['P1-Pd_distance'],
    'P2-Pd_distance': ['P2-Pd_distance'],
    # Angles
    'P1_Angle_Sum': ['P1_Angle_Sum'],
    'X_Angle_Sum': ['X_Angle_Sum'],
    'angle_PdP1RBack1': ['angle_PdP1RBack1'],
    'angle_PdP2RBack2': ['angle_PdP2RBack2'],
    'angle_R1P1Pd': ['angle_R1P1Pd'],
    'angle_R3P2Pd': ['angle_R3P2Pd'],
    'angle_R2P1Pd': ['angle_R2P1Pd'],
    'angle_R4P2Pd': ['angle_R4P2Pd'],
    'angle_R1P1R2': ['angle_R1P1R2'],
    'angle_R3P2R4': ['angle_R3P2R4'],
    'angle_R1P1RBack1': ['angle_R1P1RBack1'],
    'angle_R3P2RBack2': ['angle_R3P2RBack2'],
    'angle_R2P1RBack1': ['angle_R2P1RBack1'],
    'angle_R4P2RBack2': ['angle_R4P2RBack2'],

    ## Electronic parameters
    ## NBO
    'R1_NBO': ['R1_NBO'],
    'R2_NBO': ['R2_NBO'],
    'RBack1_NBO': ['RBack1_NBO'],
    'R3_NBO': ['R3_NBO'],
    'R4_NBO': ['R4_NBO'],
    'RBack2_NBO': ['RBack2_NBO'],
    'P1_NBO': ['P1_NBO'],
    'P2_NBO': ['P2_NBO'],
    'Cl_1_NBO': ['Cl_1_NBO'],
    'Cl_2_NBO': ['Cl_2_NBO'],
    ## NMR
    'P1_NMR': ['P1_NMR'],
    'P2_NMR': ['P2_NMR'],
    'aniso_P1_NMR': ['aniso_P1_NMR'],
    'aniso_P2_NMR': ['aniso_P2_NMR'],
    ## Bond/antibond
    'P1_Pd_bond_occ': ['P1_Pd_bond_occ'],
    'P2_Pd_bond_occ': ['P2_Pd_bond_occ'],
    'P1_Pd_bond_eng': ['P1_Pd_bond_eng'],
    'P2_Pd_bond_eng': ['P2_Pd_bond_eng'],
    'P1_Pd_antibond_occ': ['P1_Pd_antibond_occ'],
    'P2_Pd_antibond_occ': ['P2_Pd_antibond_occ'],
    'P1_Pd_antibond_eng': ['P1_Pd_antibond_eng'],
    'P2_Pd_antibond_eng': ['P2_Pd_antibond_eng'],
    'P1_R1_bond_occ': ['P1_R1_bond_occ'],
    'P2_R4_bond_occ': ['P2_R4_bond_occ'],
    'P1_R1_bond_eng': ['P1_R1_bond_eng'],
    'P2_R4_bond_eng': ['P2_R4_bond_eng'],
    'P1_R1_antibond_occ': ['P1_R1_antibond_occ'],
    'P2_R4_antibond_occ': ['P2_R4_antibond_occ'],
    'P1_R1_antibond_eng': ['P1_R1_antibond_eng'],
    'P2_R4_antibond_eng': ['P2_R4_antibond_eng'],
    'P1_R2_bond_occ': ['P1_R2_bond_occ'],
    'P2_R3_bond_occ': ['P2_R3_bond_occ'],
    'P1_R2_bond_eng': ['P1_R2_bond_eng'],
    'P2_R3_bond_eng': ['P2_R3_bond_eng'],
    'P1_R2_antibond_occ': ['P1_R2_antibond_occ'],
    'P2_R3_antibond_occ': ['P2_R3_antibond_occ'],
    'P1_R2_antibond_eng': ['P1_R2_antibond_eng'],
    'P2_R3_antibond_eng': ['P2_R3_antibond_eng'],
    'P1_RBack1_bond_occ': ['P1_RBack1_bond_occ'],
    'P2_RBack2_bond_occ': ['P2_RBack2_bond_occ'],
    'P1_RBack1_bond_eng': ['P1_RBack1_bond_eng'],
    'P2_Rback_bond_eng': ['P2_Rback_bond_eng'],
    'P1_RBack1_antibond_occ': ['P1_RBack1_antibond_occ'],
    'P2_RBack2_antibond_occ': ['P2_RBack2_antibond_occ'],
    'P1_RBack1_antibond_eng': ['P1_RBack1_antibond_eng'],
    'P2_RBack2_antibond_eng': ['P2_RBack2_antibond_eng'],
    ## NoPd Electronic parameters
    ## NBO
    'NoPd_R1_NBO': ['NoPd_R1_NBO'],
    'NoPd_R2_NBO': ['NoPd_R2_NBO'],
    'NoPd_RBack1_NBO': ['NoPd_RBack1_NBO'],
    'NoPd_R3_NBO': ['NoPd_R3_NBO'],
    'NoPd_R4_NBO': ['NoPd_R4_NBO'],
    'NoPd_RBack2_NBO': ['NoPd_RBack2_NBO'],
    'NoPd_P1_NBO': ['NoPd_P1_NBO'],
    'NoPd_P2_NBO': ['NoPd_P2_NBO'],
    ## NMR
    'NoPd_P1_NMR': ['NoPd_P1_NMR'],
    'NoPd_P2_NMR': ['NoPd_P2_NMR'],
    'NoPd_aniso_P1_NMR': ['NoPd_aniso_P1_NMR'],
    'NoPd_aniso_P2_NMR': ['NoPd_aniso_P2_NMR'],
    ## P lone pair
    'NoPd_P1_LP_occ': ['NoPd_P1_LP_occ'],
    'NoPd_P2_LP_occ': ['NoPd_P2_LP_occ'],
    'NoPd_P1_LP_eng': ['NoPd_P1_LP_eng'],
    'NoPd_P2_LP_eng': ['NoPd_P2_LP_eng'],
    'NoPd_LP_P1_s': ['NoPd_LP_P1_s'],
    'NoPd_LP_P2_s': ['NoPd_LP_P2_s'],
    ## Bond/antibond
    'NoPd_P1_R1_bond_occ': ['NoPd_P1_R1_bond_occ'],
    'NoPd_P2_R3_bond_occ': ['NoPd_P2_R3_bond_occ'],
    'NoPd_P1_R1_bond_eng': ['NoPd_P1_R1_bond_eng'],
    'NoPd_P2_R3_bond_eng': ['NoPd_P2_R3_bond_eng'],
    'NoPd_P1_R1_antibond_occ': ['NoPd_P1_R1_antibond_occ'],
    'NoPd_P2_R3_antibond_occ': ['NoPd_P2_R3_antibond_occ'],
    'NoPd_P1_R1_antibond_eng': ['NoPd_P1_R1_antibond_eng'],
    'NoPd_P2_R3_antibond_eng': ['NoPd_P2_R3_antibond_eng'],
    'NoPd_P1_R2_bond_occ': ['NoPd_P1_R2_bond_occ'],
    'NoPd_P2_R4_bond_occ': ['NoPd_P2_R4_bond_occ'],
    'NoPd_P1_R2_bond_eng': ['NoPd_P1_R2_bond_eng'],
    'NoPd_P2_R4_bond_eng': ['NoPd_P2_R4_bond_eng'],
    'NoPd_P1_R2_antibond_occ': ['NoPd_P1_R2_antibond_occ'],
    'NoPd_P2_R4_antibond_occ': ['NoPd_P2_R4_antibond_occ'],
    'NoPd_P1_R2_antibond_eng': ['NoPd_P1_R2_antibond_eng'],
    'NoPd_P2_R4_antibond_eng': ['NoPd_P2_R4_antibond_eng'],
    'NoPd_P1_RBack1_bond_occ': ['NoPd_P1_RBack1_bond_occ'],
    'NoPd_P2_RBack2_bond_occ': ['NoPd_P2_RBack2_bond_occ'],
    'NoPd_P1_RBack1_bond_eng': ['NoPd_P1_RBack1_bond_eng'],
    'NoPd_P2_RBack2_bond_eng': ['NoPd_P2_RBack2_bond_eng'],
    'NoPd_P1_RBack1_antibond_occ': ['NoPd_P1_RBack1_antibond_occ'],
    'NoPd_P2_RBack2_antibond_occ': ['NoPd_P2_RBack2_antibond_occ'],
    'NoPd_P1_RBack1_antibond_eng': ['NoPd_P1_RBack1_antibond_eng'],
    'NoPd_P2_RBack2_antibond_eng': ['NoPd_P2_RBack2_antibond_eng'],

    ##  Steric parameters
    'NE_3.0_Ang': ['NE_3.0_Ang'],
    'SW_3.0_Ang': ['SW_3.0_Ang'],
    'NW_3.0_Ang': ['NW_3.0_Ang'],
    'SE_3.0_Ang': ['SE_3.0_Ang'],
    'NE_4.0_Ang': ['NE_4.0_Ang'],
    'SW_4.0_Ang': ['SW_4.0_Ang'],
    'NW_4.0_Ang': ['NW_4.0_Ang'],
    'SE_4.0_Ang': ['SE_4.0_Ang'],
    'NE_5.0_Ang': ['NE_5.0_Ang'],
    'SW_5.0_Ang': ['SW_5.0_Ang'],
    'NW_5.0_Ang': ['NW_5.0_Ang'],
    'SE_5.0_Ang': ['SE_5.0_Ang'],
    'SE_6.0_Ang': ['SE_6.0_Ang'],
    'NE_6.0_Ang': ['NE_6.0_Ang'],
    'SW_6.0_Ang': ['SW_6.0_Ang'],
    'NW_6.0_Ang': ['NW_6.0_Ang'],
    'SE_7.0_Ang': ['SE_7.0_Ang'],
    'NE_7.0_Ang': ['NE_7.0_Ang'],
    'SW_7.0_Ang': ['SW_7.0_Ang'],
    'NW_7.0_Ang': ['NW_7.0_Ang'],
    'NE_octant_3.0_Ang': ['NE_octant_3.0_Ang'],
    'NW_octant_3.0_Ang': ['NW_octant_3.0_Ang'],
    'SE_octant_3.0_Ang': ['SE_octant_3.0_Ang'],
    'SW_octant_3.0_Ang': ['SW_octant_3.0_Ang'],
    'NE_octant_4.0_Ang': ['NE_octant_4.0_Ang'],
    'NW_octant_4.0_Ang': ['NW_octant_4.0_Ang'],
    'SE_octant_4.0_Ang': ['SE_octant_4.0_Ang'],
    'SW_octant_4.0_Ang': ['SW_octant_4.0_Ang'],
    'NE_octant_5.0_Ang': ['NE_octant_5.0_Ang'],
    'NW_octant_5.0_Ang': ['NW_octant_5.0_Ang'],
    'SE_octant_5.0_Ang': ['SE_octant_5.0_Ang'],
    'SW_octant_5.0_Ang': ['SW_octant_5.0_Ang'],
    'NE_octant_6.0_Ang': ['NE_octant_6.0_Ang'],
    'NW_octant_6.0_Ang': ['NW_octant_6.0_Ang'],
    'SE_octant_6.0_Ang': ['SE_octant_6.0_Ang'],
    'SW_octant_6.0_Ang': ['SW_octant_6.0_Ang'],
    'NE_octant_7.0_Ang': ['NE_octant_7.0_Ang'],
    'NW_octant_7.0_Ang': ['NW_octant_7.0_Ang'],
    'SE_octant_7.0_Ang': ['SE_octant_7.0_Ang'],
    'SW_octant_7.0_Ang': ['SW_octant_7.0_Ang']
}

# C2 and C2v ligands have parameters grouped related to the symmetry operations.
# With the grouped parameters, min, max, and avg are calculated.
