#!/bin/csh
#$ -N l_63_SPE_NoRh
#$ -pe smp 14
#$ -q iqtc08.q
#$ -S /bin/csh
#$ -cwd
#$ -o $HOME/javier/l_63_SPE_NoRh.log
#$ -e $HOME/javier/l_63_SPE_NoRh.err
#$ -m e  
#$ -M javier.eusamio@ub.edu 

# Load the modules needed
source /etc/profile.d/modules.csh
module load gaussian/g16b01

cd $TMPDIR
cp -pr $HOME/javier/l_63_SPE_NoRh.gjf .

# Run the job
g16 < l_63_SPE_NoRh.gjf > l_63_SPE_NoRh.out

# Copy the results to our home directory
cp l_63_SPE_NoRh.out $HOME/javier/